#!/usr/bin/python
from __future__ import division

def get_at_contentB(dna):
	length = len(dna)
	a_count = dna.upper().count('A')
	t_count = dna.upper().count('T')
	at_content = (a_count + t_count) / length
	return round (at_content, 2)
	
my_at_contentB = get_at_contentB("ATTTGGGCCCCCTTTCCC")
print(str(my_at_contentB))
print(get_at_contentB("ATTTGGGCCCCCTTTGGG"))
print(get_at_contentB("aatttttcccccgggggga"))
